[package]
name = "wg-service"
version = "0.1.0"
authors = ["boumba100 <noah.bouma@gmail.com>"]
edition = "2018"


[workspace]
members = [
    "wg-manager",
    "wg-manager-service",
    "wg-manager-service-common"
]